cp ../../../../Kaldi/src/lm/kaldi-lm.a ./libkaldi-lm.a
cp ../../../../Kaldi/src/gmm/kaldi-gmm.a ./libkaldi-gmm.a
cp ../../../../Kaldi/src/hmm/kaldi-hmm.a ./libkaldi-hmm.a
cp ../../../../Kaldi/src/kws/kaldi-kws.a ./libkaldi-kws.a
cp ../../../../Kaldi/src/lat/kaldi-lat.a ./libkaldi-lat.a
cp ../../../../Kaldi/src/base/kaldi-base.a ./libkaldi-base.a
cp ../../../../Kaldi/src/feat/kaldi-feat.a ./libkaldi-feat.a
cp ../../../../Kaldi/src/nnet/kaldi-nnet.a ./libkaldi-nnet.a
cp ../../../../Kaldi/src/tree/kaldi-tree.a ./libkaldi-tree.a
cp ../../../../Kaldi/src/util/kaldi-util.a ./libkaldi-util.a
cp ../../../../Kaldi/src/chain/kaldi-chain.a ./lib
cp ../../../../Kaldi/src/nnet2/kaldi-nnet2.a ./lib
cp ../../../../Kaldi/src/nnet3/kaldi-nnet3.a ./lib
cp ../../../../Kaldi/src/rnnlm/kaldi-rnnlm.a ./lib
cp ../../../../Kaldi/src/sgmm2/kaldi-sgmm2.a ./lib
cp ../../../../Kaldi/src/fstext/kaldi-fstext.a ./libkaldi-fstext.a
cp ../../../../Kaldi/src/matrix/kaldi-matrix.a ./libkaldi-matrix.a
cp ../../../../Kaldi/src/decoder/kaldi-decoder.a ./libkaldi-decoder.a
cp ../../../../Kaldi/src/ivector/kaldi-ivector.a ./libkaldi-ivector.a
cp ../../../../Kaldi/src/online/kaldi-online.a ./libkaldi-online.a
cp ../../../../Kaldi/src/online2/kaldi-online2.a ./libkaldi-online2.a
cp ../../../../Kaldi/src/transform/kaldi-transform.a ./libkaldi-transform.a
cp ../../../../Kaldi/tools/openfst/lib/libfst.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstfar.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstfarscript.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstlookahead.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstngram.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstscript.a .
