cp ../../../../Kaldi/src/lm/kaldi-lm.a .
cp ../../../../Kaldi/src/gmm/kaldi-gmm.a .
cp ../../../../Kaldi/src/hmm/kaldi-hmm.a .
cp ../../../../Kaldi/src/kws/kaldi-kws.a .
cp ../../../../Kaldi/src/lat/kaldi-lat.a .
cp ../../../../Kaldi/src/base/kaldi-base.a .
cp ../../../../Kaldi/src/feat/kaldi-feat.a .
cp ../../../../Kaldi/src/nnet/kaldi-nnet.a .
cp ../../../../Kaldi/src/tree/kaldi-tree.a .
cp ../../../../Kaldi/src/util/kaldi-util.a .
cp ../../../../Kaldi/src/chain/kaldi-chain.a .
cp ../../../../Kaldi/src/nnet2/kaldi-nnet2.a .
cp ../../../../Kaldi/src/nnet3/kaldi-nnet3.a .
cp ../../../../Kaldi/src/rnnlm/kaldi-rnnlm.a .
cp ../../../../Kaldi/src/sgmm2/kaldi-sgmm2.a .
cp ../../../../Kaldi/src/fstext/kaldi-fstext.a .
cp ../../../../Kaldi/src/matrix/kaldi-matrix.a .
cp ../../../../Kaldi/src/decoder/kaldi-decoder.a .
cp ../../../../Kaldi/src/ivector/kaldi-ivector.a .
cp ../../../../Kaldi/src/online2/kaldi-online2.a .
cp ../../../../Kaldi/src/transform/kaldi-transform.a .
cp ../../../../Kaldi/tools/openfst/lib/libfst.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstfar.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstfarscript.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstlookahead.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstngram.a .
cp ../../../../Kaldi/tools/openfst/lib/libfstscript.a .
